package commands

import (
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"github.com/spf13/cobra"
)

// hookScript is the shell script content written to .git/hooks/pre-commit.
// It uses a POSIX-compliant shebang so it works on Linux, macOS, and Termux.
const hookScript = `#!/usr/bin/env sh
# ┌─────────────────────────────────────────────────────────────────────┐
# │  CRENOX — Pre-Commit Security Hook                                 │
# │  Auto-generated by: crenox install                                 │
# │  Do not edit this file manually. Re-run crenox install to update. │
# └─────────────────────────────────────────────────────────────────────┘

CRENOX_BIN="{{.BinPath}}"

# If the binary path is not set or not found, look on PATH.
if [ -z "$CRENOX_BIN" ] || [ ! -x "$CRENOX_BIN" ]; then
    CRENOX_BIN=$(command -v crenox 2>/dev/null)
fi

if [ -z "$CRENOX_BIN" ]; then
    echo "crenox: hook is installed but the 'crenox' binary was not found." >&2
    echo "crenox: install it via 'go install github.com/crenoxhq/crenox/v2/cmd/crenox@latest'" >&2
    exit 1
fi

exec "$CRENOX_BIN" run "$@"
`

// NewInstallCmd builds the `crenox install` sub-command.
func NewInstallCmd() *cobra.Command {
	var (
		global  bool
		repoDir string
		force   bool
	)

	cmd := &cobra.Command{
		Use:   "install",
		Short: "Install the pre-commit hook into a Git repository",
		Long: `Install the Crenox pre-commit hook script into your Git environment.
By default, the hook is installed locally into the current Git repository. You can optionally install it globally to protect all Git repositories on your system automatically.

Installation Modes:
  1. Local Installation (Default):
     Writes the executable hook to '<repo_root>/.git/hooks/pre-commit'.
  
  2. Global Installation (--global):
     Creates a global Git hooks directory at '~/.config/crenox/hooks' and configures Git (core.hooksPath). Every repository on your machine will automatically run Crenox during commits.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if global {
				return installGlobal(force)
			}
			return installLocal(repoDir, force)
		},
	}

	cmd.Flags().BoolVar(&global, "global", false, "install globally for all repositories via git core.hooksPath")
	cmd.Flags().StringVar(&repoDir, "repo", ".", "path to the target Git repository root directory")
	cmd.Flags().BoolVarP(&force, "force", "f", false, "overwrite an existing pre-commit hook without prompting")

	return cmd
}

// installLocal writes the hook into <repoDir>/.git/hooks/pre-commit.
func installLocal(repoDir string, force bool) error {
	gitDir := filepath.Join(repoDir, ".git")
	if _, err := os.Stat(gitDir); os.IsNotExist(err) {
		return fmt.Errorf("%q is not a git repository (no .git directory found)", repoDir)
	}

	hooksDir := filepath.Join(gitDir, "hooks")
	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		return fmt.Errorf("cannot create hooks directory: %w", err)
	}

	hookPath := filepath.Join(hooksDir, "pre-commit")
	return writeHookScript(hookPath, force)
}

// installGlobal sets core.hooksPath and writes the hook to the global dir.
func installGlobal(force bool) error {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("cannot determine home directory: %w", err)
	}

	globalHooksDir := filepath.Join(homeDir, ".config", "crenox", "hooks")
	if err := os.MkdirAll(globalHooksDir, 0o755); err != nil {
		return fmt.Errorf("cannot create global hooks directory: %w", err)
	}

	hookPath := filepath.Join(globalHooksDir, "pre-commit")
	if err := writeHookScript(hookPath, force); err != nil {
		return err
	}

	// Set git's global hooksPath.
	if err := runGitConfig("core.hooksPath", globalHooksDir); err != nil {
		return fmt.Errorf("could not set git core.hooksPath: %w", err)
	}

	fmt.Printf("✔ Crenox installed globally.\n")
	fmt.Printf("  Global hooks directory: %s\n", globalHooksDir)
	fmt.Printf("  All git repositories on this machine are now protected.\n")
	return nil
}

// writeHookScript renders the hook template and writes it to hookPath.
func writeHookScript(hookPath string, force bool) error {
	if !force {
		if _, err := os.Stat(hookPath); err == nil {
			return fmt.Errorf(
				"a pre-commit hook already exists at %q (use --force to overwrite it)", hookPath)
		}
	}

	binPath, err := currentBinaryPath()
	if err != nil {
		binPath = "" // Will fall back to PATH lookup at hook runtime.
	}

	tmpl, err := template.New("hook").Parse(hookScript)
	if err != nil {
		return fmt.Errorf("internal template error: %w", err)
	}

	f, err := os.OpenFile(hookPath, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o755)
	if err != nil {
		return fmt.Errorf("cannot write hook to %q: %w", hookPath, err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, struct{ BinPath string }{BinPath: binPath}); err != nil {
		return fmt.Errorf("cannot render hook script: %w", err)
	}

	fmt.Printf("✔ Crenox hook installed at: %s\n", hookPath)
	return nil
}

// currentBinaryPath returns the absolute path of the running crenox binary.
func currentBinaryPath() (string, error) {
	exe, err := os.Executable()
	if err != nil {
		return "", err
	}
	abs, err := filepath.EvalSymlinks(exe)
	if err != nil {
		return exe, nil
	}
	return abs, nil
}

// runGitConfig wraps `git config --global key value`.
func runGitConfig(key, value string) error {
	return runCommand("git", "config", "--global", key, value)
}
